version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - msnet

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: "orders.created:1:1,orders.payment-result:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - msnet

  orders-db:
    image: postgres:13-alpine
    container_name: orders-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb
    volumes:
      - orders-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "orders-db", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - msnet

  payments-db:
    image: postgres:13-alpine
    container_name: payments-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentsdb
    volumes:
      - payments-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "payments-db", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - msnet

  orders-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: orders-service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__OrdersDb: "Host=orders-db;Database=ordersdb;Username=postgres;Password=postgres"
      Kafka__BootstrapServers: "kafka:9092"
    depends_on:
      - kafka
      - orders-db
    entrypoint:
      - sh
      - -c
      - |
        echo "Waiting for dependencies..."
        sleep 10
        exec dotnet OrdersService.dll
    restart: on-failure
    networks:
      - msnet

  payments-service:
    build:
      context: ./PaymentsService
      dockerfile: Dockerfile
    container_name: payments-service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__PaymentsDb: "Host=payments-db;Database=paymentsdb;Username=postgres;Password=postgres"
      Kafka__BootstrapServers: "kafka:9092"
    depends_on:
      - kafka
      - payments-db
    entrypoint:
      - sh
      - -c
      - |
        echo "Waiting for dependencies..."
        sleep 10
        exec dotnet PaymentsService.dll
    restart: on-failure
    networks:
      - msnet

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "80:80"
    depends_on:
      - kafka
      - orders-service
      - payments-service
    restart: on-failure
    networks:
      - msnet

volumes:
  orders-data:
  payments-data:

networks:
  msnet:
    driver: bridge